name: Start IPFS Daemon
description: Start IPFS daemon and wait for it to become ready

runs:
  using: 'composite'
  steps:
    - uses: ipfs/download-ipfs-distribution-action@v1
      with:
        cache: false
    - uses: ipfs/start-ipfs-daemon-action@v1
